ERROR - 2022-01-26 00:43:42 --> Error connecting to the database: Class 'SQLite3' not found
CRITICAL - 2022-01-26 01:49:41 --> Undefined variable: title
#0 D:\xampp\htdocs\tokobuku\app\Views\layout\template.php(10): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'D:\\xampp\\htdocs...', 10, Array)
#1 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(210): include('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(226): CodeIgniter\View\View->render('layout/template', Array, true)
#4 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('admin/overview', Array, true)
#5 D:\xampp\htdocs\tokobuku\app\Controllers\Home.php(9): view('admin/overview')
#6 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\Home->index()
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-01-26 02:45:21 --> Undefined property: Myth\Auth\Config\Auth::$activeResetter
#0 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Views\login.php(64): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp\\htdocs...', 64, Array)
#1 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(210): include('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#4 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(401): view('Myth\\Auth\\Views...', Array)
#5 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('Myth\\Auth\\Views...', Array)
#6 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->login()
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-01-26 02:47:29 --> Undefined property: Myth\Auth\Config\Auth::$activeResetter
#0 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Views\login.php(64): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp\\htdocs...', 64, Array)
#1 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(210): include('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#4 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(401): view('Myth\\Auth\\Views...', Array)
#5 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('Myth\\Auth\\Views...', Array)
#6 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->login()
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-01-26 02:47:41 --> Undefined property: Myth\Auth\Config\Auth::$activeResetter
#0 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Views\login.php(64): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp\\htdocs...', 64, Array)
#1 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(210): include('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#4 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(401): view('Myth\\Auth\\Views...', Array)
#5 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('Myth\\Auth\\Views...', Array)
#6 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->login()
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-01-26 19:23:06 --> Invalid file: App\Views\login.php
#0 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('App\\Views\\login...')
#1 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('App\\Views\\login', Array, true)
#2 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(401): view('App\\Views\\login', Array)
#3 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('App\\Views\\login', Array)
#4 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->login()
#5 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-01-26 19:23:12 --> Invalid file: \App\Views\login.php
#0 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('\\App\\Views\\logi...')
#1 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('\\App\\Views\\logi...', Array, true)
#2 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(401): view('\\App\\Views\\logi...', Array)
#3 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\logi...', Array)
#4 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->login()
#5 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-01-26 19:23:18 --> Invalid file: \App\Views\login.php
#0 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('\\App\\Views\\logi...')
#1 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('\\App\\Views\\logi...', Array, true)
#2 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(401): view('\\App\\Views\\logi...', Array)
#3 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\logi...', Array)
#4 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->login()
#5 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-01-26 19:23:29 --> Invalid file: .\App\Views\login.php
#0 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('.\\App\\Views\\log...')
#1 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('.\\App\\Views\\log...', Array, true)
#2 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(401): view('.\\App\\Views\\log...', Array)
#3 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('.\\App\\Views\\log...', Array)
#4 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->login()
#5 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#9 {main}
ERROR - 2022-01-26 22:19:34 --> Unknown column 'users.level_id' in 'on clause'
CRITICAL - 2022-01-26 22:19:34 --> Unknown column 'users.level_id' in 'on clause'
#0 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `users`....', 0)
#1 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`....')
#2 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`....')
#3 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT `users`....', Array, false)
#4 D:\xampp\htdocs\tokobuku\app\Models\GroceryCrudModel.php(89): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\tokobuku\app\Libraries\GroceryCrud.php(1223): App\Models\GroceryCrudModel->get_list()
#6 D:\xampp\htdocs\tokobuku\app\Libraries\GroceryCrud.php(1340): App\Libraries\grocery_CRUD_Model_Driver->get_list()
#7 D:\xampp\htdocs\tokobuku\app\Libraries\GroceryCrud.php(4185): App\Libraries\grocery_CRUD_Layout->showList(false, Object(stdClass))
#8 D:\xampp\htdocs\tokobuku\app\Controllers\Users.php(51): App\Libraries\GroceryCrud->render()
#9 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\Users->index()
#10 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2022-01-26 23:01:07 --> Undefined property: App\Controllers\Users::$config
#0 D:\xampp\htdocs\tokobuku\app\Controllers\Users.php(55): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp\\htdocs...', 55, Array)
#1 D:\xampp\htdocs\tokobuku\app\Controllers\Users.php(35): App\Controllers\Users->save()
#2 [internal function]: App\Controllers\Users->App\Controllers\{closure}(Object(stdClass))
#3 D:\xampp\htdocs\tokobuku\app\Libraries\GroceryCrud.php(905): call_user_func(Object(Closure), Object(stdClass))
#4 D:\xampp\htdocs\tokobuku\app\Libraries\GroceryCrud.php(4242): App\Libraries\grocery_CRUD_Model_Driver->db_insert(Object(stdClass))
#5 D:\xampp\htdocs\tokobuku\app\Controllers\Users.php(41): App\Libraries\GroceryCrud->render()
#6 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\Users->index('insert')
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-01-26 23:01:21 --> Undefined property: App\Controllers\Users::$config
#0 D:\xampp\htdocs\tokobuku\app\Controllers\Users.php(55): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp\\htdocs...', 55, Array)
#1 D:\xampp\htdocs\tokobuku\app\Controllers\Users.php(35): App\Controllers\Users->save()
#2 [internal function]: App\Controllers\Users->App\Controllers\{closure}(Object(stdClass))
#3 D:\xampp\htdocs\tokobuku\app\Libraries\GroceryCrud.php(905): call_user_func(Object(Closure), Object(stdClass))
#4 D:\xampp\htdocs\tokobuku\app\Libraries\GroceryCrud.php(4242): App\Libraries\grocery_CRUD_Model_Driver->db_insert(Object(stdClass))
#5 D:\xampp\htdocs\tokobuku\app\Controllers\Users.php(41): App\Libraries\GroceryCrud->render()
#6 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\Users->index('insert')
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-01-26 23:01:55 --> Undefined property: App\Controllers\Users::$config
#0 D:\xampp\htdocs\tokobuku\app\Controllers\Users.php(55): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp\\htdocs...', 55, Array)
#1 D:\xampp\htdocs\tokobuku\app\Controllers\Users.php(35): App\Controllers\Users->save()
#2 [internal function]: App\Controllers\Users->App\Controllers\{closure}(Object(stdClass))
#3 D:\xampp\htdocs\tokobuku\app\Libraries\GroceryCrud.php(905): call_user_func(Object(Closure), Object(stdClass))
#4 D:\xampp\htdocs\tokobuku\app\Libraries\GroceryCrud.php(4242): App\Libraries\grocery_CRUD_Model_Driver->db_insert(Object(stdClass))
#5 D:\xampp\htdocs\tokobuku\app\Controllers\Users.php(41): App\Libraries\GroceryCrud->render()
#6 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\Users->index('insert')
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-01-26 23:03:42 --> Trying to get property 'password_hash' of non-object
#0 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'D:\\xampp\\htdocs...', 165, Array)
#1 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-26 23:03:57 --> Trying to get property 'password_hash' of non-object
#0 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'D:\\xampp\\htdocs...', 165, Array)
#1 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-26 23:04:22 --> Trying to get property 'password_hash' of non-object
#0 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'D:\\xampp\\htdocs...', 165, Array)
#1 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-26 23:04:30 --> Trying to get property 'password_hash' of non-object
#0 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'D:\\xampp\\htdocs...', 165, Array)
#1 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-26 23:04:46 --> Trying to get property 'password_hash' of non-object
#0 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'D:\\xampp\\htdocs...', 165, Array)
#1 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-26 23:06:21 --> Trying to get property 'password_hash' of non-object
#0 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'D:\\xampp\\htdocs...', 165, Array)
#1 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 D:\xampp\htdocs\tokobuku\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(825): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 D:\xampp\htdocs\tokobuku\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#8 {main}
